name: CI

on: [ workflow_dispatch, push, pull_request ]

jobs:
  ci_non_nix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: $test-cache-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy check
        run: cargo clippy -- -D warnings

      - name: Build and Test
        env:
          RUST_LOG: debug
        run: cargo test --features=apple-native,windows-native --verbose

      - name: Build the CLI release
        run: cargo build --release --features=apple-native,windows-native --example keyring-cli

  ci_nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - "linux-native"
          - "sync-secret-service"
          - "linux-native,sync-secret-service"
          - "sync-secret-service,crypto-rust"
          - "sync-secret-service,crypto-openssl"
          - "async-secret-service,tokio,crypto-rust"
          - "async-secret-service,async-io,crypto-rust"
          - "async-secret-service,tokio,crypto-openssl"
          - "async-secret-service,async-io,crypto-openssl"
          - "linux-native-sync-persistent,crypto-rust"
          - "linux-native-sync-persistent,crypto-openssl"
          - "linux-native-async-persistent,tokio,crypto-rust"
          - "linux-native-async-persistent,async-io,crypto-rust"
          - "linux-native-async-persistent,tokio,crypto-openssl"
          - "linux-native-async-persistent,async-io,crypto-openssl"

    steps:
      - name: Install CI dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libdbus-1-dev libssl-dev gnome-keyring

      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: $test-cache-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Start gnome-keyring
        # run gnome-keyring with 'foobar' as password for the login keyring
        # this will create a new login keyring and unlock it
        # the login password doesn't matter, but the keyring must be unlocked for the tests to work
        run: gnome-keyring-daemon --components=secrets --daemonize --unlock <<< 'foobar'

      - name: Run tests
        env:
          RUST_LOG: debug
        # run tests single-threaded to avoid dbus race conditions
        run: cargo test --features=${{ matrix.features }} -- --test-threads=1

  ios_native:
    runs-on: macos-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-ios

      - name: Build iOS library
        run: cargo build --target aarch64-apple-ios --features=apple-native --example=iostest

  msrv_native:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install rust MSRV
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75
          components: clippy

      - name: Clippy check
        run: cargo clippy --features=linux-native -- -D warnings

  doc_build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-unknown-linux-gnu, aarch64-apple-darwin, aarch64-apple-ios, x86_64-pc-windows-msvc
          components: rust-src

      - name: docs build check
        run: bash test-docsrs-build.sh
